export interface Etablissement {
    readonly ID : number;
    readonly Identifiant_de_l_etablissement : string;
    readonly Nom_etablissement : string;
    readonly Type_etablissement : string;
    readonly Statut_public_prive : string;
    readonly Adresse_1 : string;
    readonly Adresse_2 : string;
    readonly Adresse_3 : string;
    readonly Code_postal : string;
    readonly Code_commune : string;
    readonly Nom_commune: string ;
    readonly Code_departement: string;
    readonly Code_academie: string;
    readonly Code_region: string;
    readonly Ecole_maternelle: string;
    readonly Ecole_elementaire: string;
    readonly Voie_generale: string;
    readonly Voie_technologique: string;
    readonly Voie_professionnelle: string;
    readonly Telephone: string;
    readonly Fax: string;
    readonly Web: string;
    readonly Mail: string;
    readonly Restauration: string;
    readonly Hebergement: string;
    readonly ULIS: string;
    readonly Apprentissage: string;
    readonly Segpa: string;
    readonly Section_arts: string;
    readonly Section_cinema: string;
    readonly Section_theatre: string;
    readonly Section_sport: string;
    readonly Section_internationale: string;
    readonly Section_europeenne: string;
    readonly Lycee_Agricole: string;
    readonly Lycee_militaire: string;
    readonly Lycee_des_metiers: string;
    readonly Post_BAC: string;
    readonly Appartenance_Education_Prioritaire: string;
    readonly GRETA: string;
    readonly SIREN_SIRET: string;
    readonly Nombre_d_eleves: string;
    readonly Fiche_onisep: string;
    readonly position: string;
    readonly Type_contrat_prive: string;
    readonly Libelle_departement: string;
    readonly Libelle_academie: string;
    readonly Libelle_region: string;
    readonly coordonnee_X: string;
    readonly coordonnee_Y: string;
    readonly epsg: string;
    readonly nom_circonscription: string;
    readonly latitude: number;
    readonly longitude: number;
    readonly precision_localisation: string;
    readonly date_ouverture: string;
    readonly date_maj_ligne: string;
    readonly etat: string;
    readonly ministere_tutelle: string;
    readonly etablissement_multi_lignes: string;
    readonly rpi_concentre: string;
    readonly rpi_disperse: string;
    readonly code_nature: string;
    readonly libelle_nature: string;
    readonly Code_type_contrat_prive: string;
    readonly PIAL: string;
    readonly etablissement_mere: string;
    readonly type_rattachement_etablissement_mere: string;
    readonly code_bassin_formation: string;
    readonly libelle_bassin_formation: string

}
